#!/usr/bin/env python3
"""Generate Core/app/sin_lut.h: SIN_Q15[d] = round(sin(d deg) * 32768), clamped
to 32767, for d = 0..90. Prints the header to stdout.

    python3 gen_sin_lut.py > ../Core/app/sin_lut.h
"""
import math


def main():
    vals = [min(32767, round(math.sin(math.radians(d)) * 32768)) for d in range(91)]
    out = []
    out.append("/* GENERATED by tests/gen_sin_lut.py - do not edit.")
    out.append(" * SIN_Q15[d] = round(sin(d deg) * 32768) clamped to 32767, d = 0..90. */")
    out.append("#ifndef SIN_LUT_H")
    out.append("#define SIN_LUT_H")
    out.append("#include <stdint.h>")
    out.append("")
    out.append("static const int16_t SIN_Q15[91] = {")
    for i in range(0, 91, 10):
        row = ", ".join(str(v) for v in vals[i:i + 10])
        out.append("    " + row + ("," if i + 10 < 91 else ""))
    out.append("};")
    out.append("")
    out.append("#endif")
    print("\n".join(out))


if __name__ == "__main__":
    main()
