#!/usr/bin/env python3
"""Convert a vendor PLL register export into a Core/drivers/pll_tables header.

Inputs (one register per line; blank lines and lines starting with '#' or '//'
are ignored; anything else that does not match is an error):
  lmx2594  TI TICS Pro, File > Export > "Hex Registers":   R<n><ws>0x<6 hex>
           The 24-bit frame (R/W=0, addr7, data16) is used as is; its address
           byte must equal <n> (R0..R112) and the R/W bit must be 0.
  adf4372  ADI ADF4372 software register export:           0x<4 hex> 0x<2 hex>
           word = addr15 << 8 | data8 (address 0x0000..0x7FFF).
Words keep the order of the file (programming order is the vendor tool's).

The generated header matches the pll_regs_t of Core/drivers/pll_lo.h
({words, count, settle_ms, name}) and defines PLL_TABLE_PLACEHOLDER as 0
(the checked-in placeholder headers leave it at the default 1).

Usage:
  tools/regtable_to_h.py --chip lmx2594 --name LMX2594_10500MHZ [--settle-ms 10] \\
      -o Core/drivers/pll_tables/lmx2594_10500MHz.h export.txt
"""
import argparse
import re
import sys

LMX_RE = re.compile(r"[Rr](\d+)\s+0[xX]([0-9A-Fa-f]{6})")
ADF_RE = re.compile(r"0[xX]([0-9A-Fa-f]{4})\s+0[xX]([0-9A-Fa-f]{2})")
IDENT_RE = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")
CHIPS = ("lmx2594", "adf4372")


class RegTableError(ValueError):
    pass


def parse(chip, lines):
    """Return the list of 24-bit words in file order."""
    if chip not in CHIPS:
        raise RegTableError("unknown chip {!r} (use one of {})".format(chip, ", ".join(CHIPS)))
    words = []
    for no, raw in enumerate(lines, 1):
        ln = raw.strip()
        if not ln or ln.startswith(("#", "//")):
            continue
        if chip == "lmx2594":
            m = LMX_RE.fullmatch(ln)
            if not m:
                raise RegTableError(f"line {no}: not 'R<n> 0x<6 hex>': {ln!r}")
            n, frame = int(m.group(1)), int(m.group(2), 16)
            if n > 112:
                raise RegTableError(f"line {no}: register R{n} out of range (R0..R112)")
            if frame >> 16 != n:
                raise RegTableError(f"line {no}: frame 0x{frame:06X} does not carry "
                                    f"address {n} (or R/W bit set)")
            words.append(frame)
        else:
            m = ADF_RE.fullmatch(ln)
            if not m:
                raise RegTableError(f"line {no}: not '0x<4 hex> 0x<2 hex>': {ln!r}")
            addr, data = int(m.group(1), 16), int(m.group(2), 16)
            if addr > 0x7FFF:
                raise RegTableError(f"line {no}: address 0x{addr:04X} above 0x7FFF")
            words.append(addr << 8 | data)
    if not words:
        raise RegTableError("no registers found (empty or comment-only input)")
    return words


def render(chip, name, settle_ms, words, source):
    if chip not in CHIPS:
        raise RegTableError(f"unknown chip {chip!r}")
    if not IDENT_RE.fullmatch(name):
        raise RegTableError(f"--name must be a C identifier, got {name!r}")
    if not 0 <= settle_ms <= 0xFFFF:
        raise RegTableError("--settle-ms must be 0..65535")
    if not words or any(not 0 <= w <= 0xFFFFFF for w in words):
        raise RegTableError("words must be a non-empty list of 24-bit values")
    fmt = ("R/W=0 : addr7 : data16 (frame as exported)" if chip == "lmx2594"
           else "R/W=0 : addr15 : data8  =  addr15 << 8 | data8")
    out = [
        f"/* Generated by tools/regtable_to_h.py ({chip}) from {source} -- do not edit.",
        f" * Word format, sent MSB first, 24 bits, one CS assertion per word: {fmt}.*/",
        f"#ifndef {name}_H",
        f"#define {name}_H",
        "#include <stdint.h>",
        '#include "pll_lo.h"',
        "",
        "/* Real export: not a placeholder. */",
        "#undef PLL_TABLE_PLACEHOLDER",
        "#define PLL_TABLE_PLACEHOLDER 0",
        "",
        f"static const uint32_t {name}_WORDS[] = {{",
    ]
    for i, w in enumerate(words):
        out.append("    0x{:06X}UL{}".format(w, "," if i + 1 < len(words) else ""))
    out += [
        "};",
        "",
        f"static const pll_regs_t {name} = {{",
        f"    {name}_WORDS,",
        f"    (uint16_t)(sizeof {name}_WORDS / sizeof {name}_WORDS[0]),",
        f"    {settle_ms},                          /* settle_ms after the last word */",
        f'    "{name}"',
        "};",
        "",
        "#endif",
        "",
    ]
    return "\n".join(out)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--chip", required=True, choices=CHIPS)
    ap.add_argument("--name", required=True, help="C identifier, e.g. LMX2594_10500MHZ")
    ap.add_argument("--settle-ms", type=int, default=10)
    ap.add_argument("-o", "--output", help="output header (default: stdout)")
    ap.add_argument("src", help="vendor export file")
    a = ap.parse_args(argv)
    try:
        with open(a.src, encoding="utf-8") as f:
            words = parse(a.chip, f.read().splitlines())
        text = render(a.chip, a.name, a.settle_ms, words, a.src)
    except (RegTableError, OSError):
        return 1
    if a.output:
        with open(a.output, "w", encoding="utf-8") as f:
            f.write(text)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
