`timescale 1ns / 1ps
// ============================================================================
// ref_spectrum_rom.v — precomputed reference-chirp spectra for the matched
// filter.  Replaces the per-segment "reference FFT" pass, the time-domain
// chirp ROMs and the reference latency buffer.
//
//   addr = {segment[2:0], k[LOG2N-1:0]}
//   segment 0..3 : long chirp, FFT_256 of samples [224*seg, 224*seg + 256)
//   segment 4    : short chirp (13 samples, zero-padded)
//   dout = ROM[addr] one clock after addr (synchronous read -> block RAM/ROM)
//
// Contents are generated by tb/golden/gen_ref_spectrum.py (scaling and
// conventions documented there).  Size: 2 x 1280 x 16 = 40 kbit.
// ============================================================================
module ref_spectrum_rom #(
    parameter N_FFT  = 256,
    parameter LOG2N  = 8,
    parameter N_SEG  = 5,
    parameter DATA_W = 16,
    parameter I_FILE = "ref_spectrum_i.mem",
    parameter Q_FILE = "ref_spectrum_q.mem"
)(
    input  wire                     clk,
    input  wire [LOG2N+2:0]         addr,
    output reg  signed [DATA_W-1:0] dout_i,
    output reg  signed [DATA_W-1:0] dout_q
);

reg [DATA_W-1:0] rom_i [0:N_SEG*N_FFT-1];
reg [DATA_W-1:0] rom_q [0:N_SEG*N_FFT-1];

initial begin
    $readmemh(I_FILE, rom_i);
    $readmemh(Q_FILE, rom_q);
end

always @(posedge clk) begin
    dout_i <= rom_i[addr];
    dout_q <= rom_q[addr];
end

endmodule
